tags = {
    'ssr':{
'Agielba',
'Aglovale',
'Alanaan',
'Albert',
'Aletheia',
'Alexiel',
'Alexiel (Summer)',
'Aliza',
'Altair',
'Amira',
'Andira',
'Anila',
'Anne',
'Anre',
'Anthuria',
'Anthuria (Summer)',
'Aoidos',
'Aqours First-Years',
'Aqours Second-Years',
'Aqours Third-Years',
'Arriet',
'Arulumaya',
'Arulumaya (Holiday)',
'Athena',
'Ayer',
'Azazel',
'Baal',
'Baotorda (SSR)',
'Beatrix',
'Beatrix (Themed)',
'Black Knight',
'Cagliostro',
'Cagliostro (Dark)',
'Cagliostro (Halloween)',
'Cagliostro (Summer)',
'Caim',
'Cain (Grand)',
'Carmelina',
'Catherine',
'Cerberus',
'Charioce XVII',
'Charlotta',
'Charlotta (Halloween)',
'Charlotta (Light)',
'Chat Noir',
'Christina',
'Clarisse',
'Clarisse (Holiday)',
'Clarisse (Light)',
'Clarisse (Valentine)',
'Colossus',
'Conan Edogawa',
'Cucouroux (SSR)',
'Cure Black and Cure White',
'Dante and Freiheit',
'Danua (Halloween)',
'Danua (SSR)',
'Danua (Summer)',
'De La Fille',
'De La Fille (Earth)',
'De La Fille (Summer)',
'Diantha (Summer)',
'Dorothy and Claudia',
'Drang',
'Eahta',
'Estarriola',
'Eugen (Grand)',
'Europa',
'Europa (Summer)',
'Eustace',
'Eustace (Dark)',
'Eustace (Halloween)',
'Feena',
'Feower',
'Ferry (Grand)',
'Ferry (SSR)',
'Fif',
'Forte',
'Fraux',
'Freezie',
'Gachapin',
'Gawain',
'Geisenborger',
'Ghandagoza',
'Grea',
'Grea (Summer)',
'Grimnir',
'Grimnir (Valentine)',
'Haaselia',
'Hallessena',
'Hallessena (Halloween)',
'Halluel and Malluel (Summer)',
'Helel ben Shalem',
'Heles',
'Heles (Summer)',
'Heles (Wind)',
'Ilsa',
'Ilsa (Light)',
'Ilsa (Summer)',
'Io (Grand)',
'Io (Summer)',
'Izmir',
'Izmir (Summer)',
'Jeanne d\'Arc',
'Jeanne d\'Arc (Dark)',
'Jeanne d\'Arc (Grand)',
'Jeanne d\'Arc (Themed)',
'Jessica (Themed)',
'Jin',
'Joker',
'Juliet',
'Kallen Kouzuki',
'Karyl',
'Katalina (Grand)',
'Katalina (Promo)',
'Katzelia',
'Kokkoro',
'Kolulu',
'Korwa',
'Korwa (Summer)',
'Kou',
'Kumbhira',
'Ladiva (SSR)',
'Lady Grey',
'Lady Grey (Halloween)',
'Lady Katapillar and Vira',
'Lancelot',
'Lancelot (Wind)',
'Lancelot and Vane',
'Lecia (Grand)',
'Lecia (Water)',
'Lelouch Lamperouge',
'Lennah',
'Levi',
'Levin Sisters',
'Lilele',
'Lily',
'Lobelia',
'Lucio',
'Lucius (SSR)',
'Lunalu (SSR)',
'Macula Marius',
'Magisa',
'Magisa (Holiday)',
'Mahira',
'Maria Theresa',
'Marquiares',
'Mary (Holiday)',
'Medusa',
'Medusa (Promo)',
'Medusa (Valentine)',
'Melissabelle',
'Melissabelle (Valentine)',
'Melleau',
'Meteon (Holiday)',
'Metera',
'Metera (Fire)',
'Metera (Holiday)',
'Mikazuki Munechika',
'Monika',
'Monika (Grand)',
'Morrigna',
'Mugen',
'Naoise (Summer)',
'Narmaya',
'Narmaya (Holiday)',
'Narmaya (Summer)',
'Nemone',
'Nezahualpilli',
'Nicholas',
'Nier',
'Nina Drango',
'Niyon',
'Noa (Grand)',
'Olivia',
'Orchid',
'Pecorine',
'Percival',
'Percival (Summer)',
'Petra (SSR)',
'Pholia',
'Rackam (Grand)',
'Razia',
'Rei',
'Robomi',
'Romeo',
'Rosamia (SSR)',
'Rosetta (Grand)',
'Rosetta (Holiday)',
'Rosetta (Summer)',
'Sakura Kinomoto',
'Sandalphon (Event)',
'Sandalphon (Summer)',
'Sara',
'Sara (Light)',
'Sarunan',
'Sarunan (Dark)',
'Scathacha',
'Scathacha (Valentine)',
'Selfira',
'Sen (SSR)',
'Seofon',
'Seox',
'Seox (Event)',
'Seruel',
'Seruel (Holiday)',
'Shitori',
'Shiva',
'Siegfried',
'Siegfried (Fire)',
'Siegfried (Summer)',
'Silva',
'Silva (Light)',
'Societte',
'Societte (Fire)',
'Societte (Wind)',
'Sophia',
'Soriz (SSR)',
'Stan and Aliza',
'Sturm',
'Suzaku Kururugi',
'Tabina',
'Tanya (SSR)',
'Teena (Summer)',
'Therese (SSR)',
'Threo',
'Tiamat',
'Tien',
'Tsubasa',
'Tweyen',
'Vajra',
'Vane (SSR)',
'Vania',
'Vania and Malinda',
'Vaseraga',
'Vaseraga (Earth)',
'Veight',
'Vikala',
'Vira (Grand)',
'Vira (Promo)',
'Vira (SSR)',
'Vira (Summer)',
'Vira (Wind)',
'Wulf and Renie',
'Yggdrasil',
'Yngwie',
'Yodarha (SSR)',
'Yodarha (Wind)',
'Yuel',
'Yuel (Themed)',
'Yuel (Water)',
'Yuisis',
'Yuisis (Fire)',
'Yurius',
'Zahlhamelina',
'Zeta',
'Zeta (Dark)',
'Zeta (Summer)',
'Zeta and Vaseraga (Halloween)',
'Zooey',
'Zooey (Grand)',
'Zooey (Promo)',
'Μ\'s First-Years',
'Μ\'s Second-Years',
'Μ\'s Third-Years'
},
    'sr':{
    'Abby',
    'Airi Totoki',
    'Albert (Event)',
    'Alec',
    'Aliza (Event)',
    'Aliza (Water)',
    'Almeida',
    'Almeida (Summer)',
    'Amira (Promo)',
    'Anastasia',
    'Andira (Event)',
    'Ange',
    'Ange (Halloween)',
    'Anila (Event)',
    'Anna (SR)',
    'Anzu Futaba',
    'Arisa',
    'Arthur (Event)',
    'Arthur and Mordred',
    'Arulumaya (Summer)',
    'Arusha',
    'Aster',
    'Aster (Event)',
    'Augusta',
    'Ayer (Summer)',
    'Baotorda',
    'Barawa (Event)',
    'Barawa (SR)',
    'Beatrix (Halloween)',
    'Beatrix (SR)',
    'Blazing Teacher Elmott',
    'Bridgette and Cordelia',
    'Cagliostro (Event)',
    'Cailana (SR)',
    'Cain',
    'Camieux (Summer)',
    'Carmelina (SR)',
    'Carren',
    'Carren (Event)',
    'Cassius (Event)',
    'Cassius (Summer)',
    'Catherine (SR)',
    'Cecile',
    'Ceylan (Event)',
    'Charlotta (Event)',
    'Charlotta (Summer)',
    'Chloe (Summer)',
    'Chun-Li',
    'Claudia',
    'Cucouroux',
    'Daetta (SR)',
    'Dante (SR)',
    'Danua',
    'Deliford (SR)',
    'Diantha (Promo)',
    'Dorothy',
    'Ejaeli',
    'Elize Lutus',
    'Elmott',
    'Elmott (Summer)',
    'Elta',
    'Elta (Light)',
    'Erica Fontaine',
    'Erin',
    'Eso (SR)',
    'Eugen',
    'Eugen (Summer)',
    'Ezecrain',
    'Ezecrain (Event)',
    'Farrah (Event)',
    'Farrah (SR)',
    'Farrah (Summer)',
    'Feather (Halloween)',
    'Feather (SR)',
    'Feena (Event)',
    'Feena (Holiday)',
    'Ferry',
    'Ferry (Halloween)',
    'Friday (Summer)',
    'Galadar (SR)',
    'Gayne',
    'Gemini Sunrise',
    'Ghandagoza (Summer)',
    'Goblin Mage',
    'Grea (Event)',
    'Haohmaru',
    'Hazen (SR)',
    'Helnar',
    'Helnar (Summer)',
    'Herja (SR)',
    'Io',
    'Ippatsu (SR)',
    'Izuminokami Kanesada',
    'J.J.',
    'J.J. (Summer)',
    'Jamil',
    'Jamil (Dark)',
    'Jasmine (SR)',
    'Jeanne d'Arc (SR)',
    'Jessica',
    'Jessica (Event)',
    'Jessica (Summer)',
    'Jin (Event)',
    'Jin (Ronin)',
    'Jin (Themed)',
    'Jin (Wind)',
    'Johann',
    'Johann (Event)',
    'Joy (Event)',
    'Juri',
    'Juri (Event)',
    'Kanako Mimura',
    'Kaoru Sakuraba',
    'Karin',
    'Karteira (SR)',
    'Karva (SR)',
    'Katalina',
    'Katalina (Summer)',
    'Keehar',
    'Korwa (SR)',
    'Koume Shirasaka',
    'Krugne (SR)',
    'Kumbhira (Event)',
    'La Coiffe (SR)',
    'Ladiva',
    'Ladiva (Holiday)',
    'Laguna',
    'Lamretta',
    'Lamretta (Water)',
    'Lancelot (Event)',
    'Lancelot and Vane (Summer)',
    'Lecia',
    'Lecia (Summer)',
    'Leona',
    'Leona (Summer)',
    'Lilele (Summer)',
    'Lily (Event)',
    'Lina',
    'Lowain (Event)',
    'Lucius',
    'Lucius (Fire)',
    'Ludmila',
    'Luna',
    'Lyria (Event)',
    'Mahira (Event)',
    'Malinda (Event)',
    'Mariah',
    'Mary (SR)',
    'Meteon (Event)',
    'Mika Jougasaki',
    'Mikasa',
    'Miku Maekawa',
    'Milla Maxwell',
    'Milleore',
    'Mimlemel',
    'Mimlemel and Pun-Kin (Halloween)',
    'Mimlemel and Stumpeye',
    'Mina',
    'Minami Nitta',
    'Mio Honda',
    'Miria Akagi',
    'Mirin',
    'Mirin (Light)',
    'Mishra',
    'Mizuki Kawashima',
    'Morphe and Phoebe (Event)',
    'Naga',
    'Nakoruru',
    'Naoise',
    'Naoise (Event)',
    'Narmaya (Valentine)',
    'Nezahualpilli (SR)',
    'Nicholas (Event)',
    'Noa',
    'Novei',
    'Olivia (Event)',
    'Owen',
    'Pamela',
    'Paris (Event)',
    'Pengy',
    'Pengy (Event)',
    'Percival (Event)',
    'Philosophia (SR)',
    'Predator',
    'Rackam',
    'Rackam (Holiday)',
    'Randall (SR)',
    'Ranko Kanzaki',
    'Rashid',
    'Razia (SR)',
    'Redluck',
    'Reinhardtzar',
    'Richard (SR)',
    'Rika Jougasaki',
    'Rin Shibuya',
    'Rita',
    'Robertina',
    'Robomi (Event)',
    'Romeo (Event)',
    'Rosamia (SR)',
    'Rosetta',
    'Rosine (SR)',
    'Ryan (SR)',
    'Ryu',
    'Sachiko Koshimizu',
    'Sahli Lao',
    'Sakura Shinguji',
    'Sara (Event)',
    'Sara (Summer)',
    'Sarya',
    'Sarya (Event)',
    'Selfira (Event)',
    'Sen',
    'Sen (Holiday)',
    'Sevastien',
    'Sevilbarra',
    'Sevilbarra (Event)',
    'Shao',
    'Shiki Ichinose',
    'Sig',
    'Sig (Event)',
    'Skull',
    'Skull (Event)',
    'Sophia (SR)',
    'Sophie',
    'Soriz',
    'Soriz (Event)',
    'Stahn Aileron',
    'Stan (Event)',
    'Suframare (Summer)',
    'Sutera',
    'Sutera (Event)',
    'Sutera (Fire)',
    'Syr (Event)',
    'Tanya (SR)',
    'Tanya (Summer)',
    'Tear Grants',
    'Teena',
    'Teena (Valentine)',
    'Teru Tendo',
    'The Lowain Bros',
    'Therese',
    'Therese (Event)',
    'Tōru Amuro',
    'Tsubasa Kashiwagi',
    'Tyre',
    'Ulamnuran',
    'Uzuki Shimamura',
    'Vane',
    'Vane (Event)',
    'Vania (SR)',
    'Vanzza (SR)',
    'Vermeil (SR)',
    'Vira',
    'Volenna (Event)',
    'Walder (Event)',
    'Will (SR)',
    'Yaia',
    'Yaia (Holiday)',
    'Yamanbagiri Kunihiro',
    'You (Event)',
    'Yuel (Event)',
    'Yuisis (Summer)',
    'Yuri Lowell',
    'Zaja',
    'Zaja (Halloween)',
    'Zehek (Event)',
    'Zeta (Event)',
    'Zooey (Event)'
},
    'r':{
    'Alistair',
    'Anna',
    'Anna (Summer)',
    'Bakura',
    'Balurga',
    'Barawa',
    'Bridgette',
    'Cailana',
    'Camieux',
    'Camieux (Earth)',
    'Chloe',
    'Cordelia',
    'Daetta',
    'Dante',
    'Deliford',
    'Drusilla',
    'Elmelaura',
    'Eso',
    'Farrah',
    'Feather',
    'Flesselles',
    'Galadar',
    'Garma',
    'Hazen',
    'Herja',
    'Ippatsu',
    'Ippatsu (Summer)',
    'Jasmine',
    'Joel',
    'Karteira',
    'Karva',
    'Krugne',
    'La Coiffe',
    'Lamretta (R)',
    'Leonora',
    'Lowain',
    'Lowain (Summer)',
    'Lunalu',
    'Lunalu (Summer)',
    'Mary',
    'Mary (Summer)',
    'Nene',
    'Norcel',
    'Pavidus',
    'Petra',
    'Philosophia',
    'Randall',
    'Richard',
    'Rosamia',
    'Rosine',
    'Ryan',
    'Spinnah',
    'Stan',
    'Suframare',
    'Tanya',
    'Thelonim',
    'Vanzza',
    'Vermeil',
    'Viceroy',
    'Volenna',
    'Walder',
    'Walder (Holiday)',
    'Walder (Summer)',
    'Will',
    'Yodarha',
    'Young Cat (Event)',
    'Zehek'
},
    'fire':{
    'Zooey (Event)',
    'Zeta',
    'Zahlhamelina',
    'Yuisis (Fire)',
    'Yuel',
    'Vira (Promo)',
    'Viceroy',
    'Tsubasa',
    'Tien',
    'Therese (SSR)',
    'Therese',
    'Teru Tendo',
    'Teena (Valentine)',
    'Teena (Summer)',
    'Teena',
    'Tabina',
    'Sutera (Fire)',
    'Sutera (Event)',
    'Sturm',
    'Stahn Aileron',
    'Societte (Fire)',
    'Siegfried (Fire)',
    'Shiva',
    'Sen',
    'Scathacha (Valentine)',
    'Sarya (Event)',
    'Ryan (SR)',
    'Ryan',
    'Rosine (SR)',
    'Rosine',
    'Rika Jougasaki',
    'Reinhardtzar',
    'Rackam (Grand)',
    'Rackam',
    'Percival (Summer)',
    'Percival (Event)',
    'Percival',
    'Nina Drango',
    'Naoise (Event)',
    'Mugen',
    'Miria Akagi',
    'Mio Honda',
    'Milla Maxwell',
    'Metera (Fire)',
    'Mary (Summer)',
    'Mary (SR)',
    'Mary',
    'Magisa',
    'Lucius (Fire)',
    'Lina',
    'Lancelot and Vane',
    'Lamretta (R)',
    'Karva (SR)',
    'Karva',
    'Karin',
    'Kallen Kouzuki',
    'Jessica (Summer)',
    'Jessica (Event)',
    'Izuminokami Kanesada',
    'Ippatsu (Summer)',
    'Ippatsu (SR)',
    'Ippatsu',
    'Io (Summer)',
    'Ilsa (Summer)',
    'Heles',
    'Grea (Event)',
    'Grea',
    'Ghandagoza (Summer)',
    'Ghandagoza',
    'Gemini Sunrise',
    'Friday (Summer)',
    'Fraux',
    'Flesselles',
    'Ezecrain',
    'Elmott (Summer)',
    'Elmott',
    'Elmelaura',
    'Drusilla',
    'Dorothy',
    'Danua (Halloween)',
    'Dante (SR)',
    'Dante',
    'Cucouroux',
    'Colossus',
    'Clarisse',
    'Charioce XVII',
    'Cecile',
    'Cassius (Summer)',
    'Carren (Event)',
    'Carren',
    'Camieux',
    'Blazing Teacher Elmott',
    'Beatrix (Themed)',
    'Beatrix (Halloween)',
    'Barawa (Event)',
    'Barawa',
    'Athena',
    'Aster',
    'Aqours Third-Years',
    'Aoidos',
    'Anthuria',
    'Anna (Summer)',
    'Anna (SR)',
    'Anna',
    'Anila (Event)',
    'Anila',
    'Aliza (Event)',
    'Aliza',
    'Alec',
    'Alanaan',
    'Agielba',
    'Abby'
},
    'water':{
    'Aglovale',
    'Alistair',
    'Aliza (Water)',
    'Altair',
    'Anastasia',
    'Ange',
    'Anne',
    'Anre',
    'Aqours Second-Years',
    'Arulumaya (Holiday)',
    'Bridgette',
    'Cagliostro (Summer)',
    'Cailana',
    'Cailana (SR)',
    'Camieux (Summer)',
    'Charlotta',
    'Charlotta (Summer)',
    'Chat Noir',
    'Chun-Li',
    'Cucouroux (SSR)',
    'Deliford',
    'Diantha (Promo)',
    'Diantha (Summer)',
    'Drang',
    'Ejaeli',
    'Erin',
    'Europa',
    'Europa (Summer)',
    'Farrah (Summer)',
    'Feower',
    'Grea (Summer)',
    'Haaselia',
    'Io',
    'Izmir',
    'Izmir (Summer)',
    'Joel',
    'Kaoru Sakuraba',
    'Katalina',
    'Katalina (Grand)',
    'Katalina (Summer)',
    'Lady Katapillar and Vira',
    'Lamretta (Water)',
    'Lancelot',
    'Lancelot (Event)',
    'Lecia (Water)',
    'Leona (Summer)',
    'Lilele',
    'Lilele (Summer)',
    'Lily',
    'Lily (Event)',
    'Lowain (Event)',
    'Macula Marius',
    'Maria Theresa',
    'Milleore',
    'Mina',
    'Minami Nitta',
    'Mishra',
    'Mizuki Kawashima',
    'Morphe and Phoebe (Event)',
    'Naga',
    'Narmaya (Summer)',
    'Owen',
    'Pamela',
    'Pengy',
    'Pengy (Event)',
    'Pholia',
    'Randall',
    'Richard',
    'Rin Shibuya',
    'Romeo',
    'Romeo (Event)',
    'Sahli Lao',
    'Sandalphon (Summer)',
    'Sig',
    'Sig (Event)',
    'Silva',
    'Societte',
    'Suframare',
    'Suframare (Summer)',
    'Therese (Event)',
    'Ulamnuran',
    'Vajra',
    'Vane',
    'Vane (Event)',
    'Vane (SSR)',
    'Vania and Malinda',
    'Yngwie',
    'Yodarha',
    'Yodarha (SSR)',
    'Yuel (Event)',
    'Yuel (Water)'
},
    'earth':{
    'Airi Totoki',
    'Aletheia',
    'Alexiel',
    'Alexiel (Summer)',
    'Almeida',
    'Almeida (Summer)',
    'Anzu Futaba',
    'Aqours First-Years',
    'Arulumaya',
    'Augusta',
    'Ayer',
    'Ayer (Summer)',
    'Baal',
    'Balurga',
    'Beatrix (SR)',
    'Cagliostro',
    'Caim',
    'Cain',
    'Cain (Grand)',
    'Camieux (Earth)',
    'Carmelina (SR)',
    'Catherine',
    'Catherine (SR)',
    'Clarisse (Holiday)',
    'Claudia',
    'Dante and Freiheit',
    'De La Fille (Earth)',
    'Eahta',
    'Eugen',
    'Eugen (Grand)',
    'Eugen (Summer)',
    'Eustace',
    'Eustace (Halloween)',
    'Farrah',
    'Farrah (SR)',
    'Galadar',
    'Galadar (SR)',
    'Garma',
    'Gayne',
    'Hallessena',
    'Herja',
    'Herja (SR)',
    'Ilsa',
    'J.J. (Summer)',
    'Jamil',
    'Jasmine',
    'Jasmine (SR)',
    'Jessica',
    'Jessica (Themed)',
    'Jin',
    'Jin (Event)',
    'Jin (Ronin)',
    'Jin (Themed)',
    'Juri (Event)',
    'Kanako Mimura',
    'La Coiffe',
    'La Coiffe (SR)',
    'Ladiva',
    'Ladiva (SSR)',
    'Laguna',
    'Lamretta',
    'Lancelot and Vane (Summer)',
    'Leona',
    'Lobelia',
    'Magisa (Holiday)',
    'Mahira',
    'Mahira (Event)',
    'Mariah',
    'Medusa',
    'Medusa (Promo)',
    'Medusa (Valentine)',
    'Melleau',
    'Mimlemel and Pun-Kin (Halloween)',
    'Narmaya (Holiday)',
    'Nemone',
    'Nene',
    'Nezahualpilli (SR)',
    'Norcel',
    'Paris (Event)',
    'Rackam (Holiday)',
    'Razia',
    'Razia (SR)',
    'Redluck',
    'Rosetta (Summer)',
    'Sara',
    'Sara (Event)',
    'Sara (Summer)',
    'Siegfried',
    'Skull (Event)',
    'Soriz',
    'Soriz (SSR)',
    'The Lowain Bros',
    'Threo',
    'Vanzza',
    'Vanzza (SR)',
    'Vaseraga (Earth)',
    'Vira (Summer)',
    'Volenna',
    'Volenna (Event)',
    'Walder',
    'Walder (Event)',
    'Walder (Holiday)',
    'Walder (Summer)',
    'Yaia',
    'Yamanbagiri Kunihiro',
    'Yggdrasil',
    'Zaja (Halloween)',
    'Zeta and Vaseraga (Halloween)'},
    'wind':{
    'Andira',
    'Andira (Event)',
    'Arisa',
    'Arriet',
    'Arthur (Event)',
    'Arthur and Mordred',
    'Aster (Event)',
    'Carmelina',
    'Charlotta (Event)',
    'Chloe',
    'Chloe (Summer)',
    'Christina',
    'Elta',
    'Eso',
    'Eso (SR)',
    'Estarriola',
    'Farrah (Event)',
    'Feena',
    'Feena (Event)',
    'Gachapin',
    'Gawain',
    'Goblin Mage',
    'Grimnir',
    'Grimnir (Valentine)',
    'Haohmaru',
    'Hazen',
    'Hazen (SR)',
    'Heles (Wind)',
    'Helnar',
    'Helnar (Summer)',
    'Jeanne d\'Arc (Themed)',
    'Jin (Wind)',
    'Joy (Event)',
    'Juri',
    'Karteira',
    'Karteira (SR)',
    'Katzelia',
    'Keehar',
    'Kokkoro',
    'Korwa',
    'Korwa (SR)',
    'Korwa (Summer)',
    'Krugne',
    'Krugne (SR)',
    'Lancelot (Wind)',
    'Lecia',
    'Lecia (Grand)',
    'Lecia (Summer)',
    'Lennah',
    'Leonora',
    'Levi',
    'Melissabelle',
    'Meteon (Event)',
    'Meteon (Holiday)',
    'Metera',
    'Mikasa',
    'Miku Maekawa',
    'Mimlemel',
    'Mimlemel and Stumpeye',
    'Mirin',
    'Monika',
    'Monika (Grand)',
    'Morrigna',
    'Nezahualpilli',
    'Niyon',
    'Pavidus',
    'Petra',
    'Petra (SSR)',
    'Rashid',
    'Robertina',
    'Rosetta',
    'Rosetta (Grand)',
    'Ryu',
    'Sakura Shinguji',
    'Scathacha',
    'Selfira',
    'Selfira (Event)',
    'Sen (Holiday)',
    'Sen (SSR)',
    'Seofon',
    'Seruel (Holiday)',
    'Sevastien',
    'Sevilbarra',
    'Shiki Ichinose',
    'Siegfried (Summer)',
    'Societte (Wind)',
    'Spinnah',
    'Stan',
    'Stan and Aliza',
    'Sutera',
    'Suzaku Kururugi',
    'Syr (Event)',
    'Thelonim',
    'Tiamat',
    'Tōru Amuro',
    'Tsubasa Kashiwagi',
    'Tyre',
    'Vira (Wind)',
    'Yaia (Holiday)',
    'Yodarha (Wind)',
    'Yuel (Themed)',
    'Yuisis',
    'Yuisis (Summer)',
    'Yurius',
    'Μ\'s First-Years'
},
    'light':{
    'Albert',
    'Albert (Event)',
    'Amira',
    'Amira (Promo)',
    'Arusha',
    'Baotorda',
    'Baotorda (SSR)',
    'Barawa (SR)',
    'Bridgette and Cordelia',
    'Ceylan (Event)',
    'Charlotta (Halloween)',
    'Charlotta (Light)',
    'Clarisse (Light)',
    'Conan Edogawa',
    'Cordelia',
    'Cure Black and Cure White',
    'Daetta',
    'Daetta (SR)',
    'Danua (SSR)',
    'De La Fille',
    'De La Fille (Summer)',
    'Dorothy and Claudia',
    'Elta (Light)',
    'Erica Fontaine',
    'Ezecrain (Event)',
    'Feather',
    'Feather (SR)',
    'Feena (Holiday)',
    'Ferry',
    'Ferry (Halloween)',
    'Ferry (SSR)',
    'Fif',
    'Geisenborger',
    'Hallessena (Halloween)',
    'Halluel and Malluel (Summer)',
    'Heles (Summer)',
    'Ilsa (Light)',
    'Io (Grand)',
    'J.J.',
    'Jeanne d\'Arc',
    'Jeanne d\'Arc (Grand)',
    'Jeanne d\'Arc (SR)',
    'Johann',
    'Johann (Event)',
    'Juliet',
    'Kumbhira',
    'Kumbhira (Event)',
    'Ladiva (Holiday)',
    'Levin Sisters',
    'Lucio',
    'Mary (Holiday)',
    'Melissabelle (Valentine)',
    'Metera (Holiday)',
    'Mikazuki Munechika',
    'Mirin (Light)',
    'Nakoruru',
    'Naoise',
    'Naoise (Summer)',
    'Nicholas (Event)',
    'Noa',
    'Noa (Grand)',
    'Novei',
    'Pecorine',
    'Philosophia',
    'Philosophia (SR)',
    'Robomi',
    'Robomi (Event)',
    'Rosamia',
    'Rosamia (SR)',
    'Rosamia (SSR)',
    'Sachiko Koshimizu',
    'Sakura Kinomoto',
    'Sandalphon (Event)',
    'Sara (Light)',
    'Sarunan',
    'Sarya',
    'Seruel',
    'Sevilbarra (Event)',
    'Shitori',
    'Silva (Light)',
    'Sophia',
    'Sophia (SR)',
    'Sophie',
    'Soriz (Event)',
    'Tear Grants',
    'Tweyen',
    'Uzuki Shimamura',
    'Vermeil',
    'Vermeil (SR)',
    'Vira (Grand)',
    'Zeta (Event)',
    'Zeta (Summer)',
    'Zooey',
    'Zooey (Promo)',
    'Μ\'s Second-Years'
},
    'dark':{
    'Ange (Halloween)',
    'Anthuria (Summer)',
    'Arulumaya (Summer)',
    'Azazel',
    'Bakura',
    'Beatrix',
    'Black Knight',
    'Cagliostro (Dark)',
    'Cagliostro (Event)',
    'Cagliostro (Halloween)',
    'Cassius (Event)',
    'Cerberus',
    'Clarisse (Valentine)',
    'Danua',
    'Danua (Summer)',
    'Deliford (SR)',
    'Elize Lutus',
    'Eustace (Dark)',
    'Feather (Halloween)',
    'Ferry (Grand)',
    'Forte',
    'Freezie',
    'Helel ben Shalem',
    'Jamil (Dark)',
    'Jeanne d\'Arc (Dark)',
    'Joker',
    'Karyl',
    'Katalina (Promo)',
    'Kolulu',
    'Kou',
    'Koume Shirasaka',
    'Lady Grey',
    'Lady Grey (Halloween)',
    'Lelouch Lamperouge',
    'Lowain',
    'Lowain (Summer)',
    'Lucius',
    'Lucius (SSR)',
    'Ludmila',
    'Luna',
    'Lunalu',
    'Lunalu (SSR)',
    'Lunalu (Summer)',
    'Marquiares',
    'Mika Jougasaki',
    'Narmaya',
    'Narmaya (Valentine)',
    'Nicholas',
    'Nier',
    'Olivia',
    'Olivia (Event)',
    'Orchid',
    'Predator',
    'Randall (SR)',
    'Ranko Kanzaki',
    'Rei',
    'Richard (SR)',
    'Rita',
    'Rosetta (Holiday)',
    'Sarunan (Dark)',
    'Seox',
    'Seox (Event)',
    'Shao',
    'Skull',
    'Stan (Event)',
    'Tanya',
    'Tanya (SR)',
    'Tanya (SSR)',
    'Tanya (Summer)',
    'Vania',
    'Vania (SR)',
    'Vaseraga',
    'Veight',
    'Vikala',
    'Vira',
    'Vira (SSR)',
    'Will',
    'Will (SR)',
    'Wulf and Renie',
    'You (Event)',
    'Yuri Lowell',
    'Zaja',
    'Zehek',
    'Zehek (Event)',
    'Zeta (Dark)',
    'Zooey (Grand)',
    'Μ\'s Third-Years'
},
    'any':{
    'Lyria (Event)',
    'Malinda (Event)',
    'Young Cat (Event)'
},
    'human':{
    'Abby',
    'Aglovale',
    'Airi Totoki',
    'Albert',
    'Albert (Event)',
    'Alec',
    'Aletheia',
    'Altair',
    'Anastasia',
    'Ange',
    'Ange (Halloween)',
    'Anna',
    'Anna (SR)',
    'Anna (Summer)',
    'Anne',
    'Anzu Futaba',
    'Aoidos',
    'Aqours First-Years',
    'Aqours Second-Years',
    'Aqours Third-Years',
    'Arriet',
    'Arthur (Event)',
    'Arthur and Mordred',
    'Ayer',
    'Ayer (Summer)',
    'Beatrix',
    'Beatrix (Halloween)',
    'Beatrix (SR)',
    'Beatrix (Themed)',
    'Black Knight',
    'Bridgette and Cordelia',
    'Cagliostro',
    'Cagliostro (Dark)',
    'Cagliostro (Event)',
    'Cagliostro (Halloween)',
    'Cagliostro (Summer)',
    'Caim',
    'Cain',
    'Cain (Grand)',
    'Carren',
    'Carren (Event)',
    'Charioce XVII',
    'Chat Noir',
    'Christina',
    'Chun-Li',
    'Clarisse',
    'Clarisse (Holiday)',
    'Clarisse (Light)',
    'Clarisse (Valentine)',
    'Claudia',
    'Conan Edogawa',
    'Cordelia',
    'Cucouroux',
    'Cucouroux (SSR)',
    'Cure Black and Cure White',
    'Dante',
    'Dante (SR)',
    'Dante and Freiheit',
    'De La Fille',
    'De La Fille (Earth)',
    'De La Fille (Summer)',
    'Deliford',
    'Deliford (SR)',
    'Diantha (Promo)',
    'Diantha (Summer)',
    'Dorothy',
    'Dorothy and Claudia',
    'Ejaeli',
    'Elize Lutus',
    'Elta',
    'Elta (Light)',
    'Erica Fontaine',
    'Eso',
    'Eso (SR)',
    'Eugen',
    'Eugen (Grand)',
    'Eugen (Summer)',
    'Ezecrain',
    'Ezecrain (Event)',
    'Farrah',
    'Farrah (Event)',
    'Farrah (SR)',
    'Farrah (Summer)',
    'Feather',
    'Feather (Halloween)',
    'Feather (SR)',
    'Feena',
    'Feena (Event)',
    'Feena (Holiday)',
    'Friday (Summer)',
    'Gawain',
    'Gayne',
    'Gemini Sunrise',
    'Haohmaru',
    'Hazen',
    'Hazen (SR)',
    'Herja',
    'Herja (SR)',
    'Io',
    'Io (Grand)',
    'Io (Summer)',
    'Ippatsu',
    'Ippatsu (SR)',
    'Ippatsu (Summer)',
    'J.J.',
    'J.J. (Summer)',
    'Jamil',
    'Jamil (Dark)',
    'Jasmine',
    'Jasmine (SR)',
    'Jeanne d\'Arc',
    'Jeanne d\'Arc (Dark)',
    'Jeanne d\'Arc (Grand)',
    'Jeanne d\'Arc (SR)',
    'Jeanne d\'Arc (Themed)',
    'Jessica',
    'Jessica (Event)',
    'Jessica (Summer)',
    'Jessica (Themed)',
    'Jin',
    'Jin (Event)',
    'Jin (Ronin)',
    'Jin (Themed)',
    'Jin (Wind)',
    'Joel',
    'Johann',
    'Johann (Event)',
    'Joker',
    'Juliet',
    'Juri',
    'Juri (Event)',
    'Kallen Kouzuki',
    'Kanako Mimura',
    'Kaoru Sakuraba',
    'Karin',
    'Katalina',
    'Katalina (Grand)',
    'Katalina (Promo)',
    'Katalina (Summer)',
    'Kolulu',
    'Koume Shirasaka',
    'Lady Grey',
    'Lady Grey (Halloween)',
    'Lancelot',
    'Lancelot (Event)',
    'Lancelot (Wind)',
    'Lancelot and Vane',
    'Lancelot and Vane (Summer)',
    'Lecia',
    'Lecia (Grand)',
    'Lecia (Summer)',
    'Lecia (Water)',
    'Lelouch Lamperouge',
    'Lennah',
    'Leona',
    'Leona (Summer)',
    'Levi',
    'Levin Sisters',
    'Lina',
    'Lobelia',
    'Lucius',
    'Lucius (Fire)',
    'Lucius (SSR)',
    'Luna',
    'Lyria (Event)',
    'Magisa',
    'Magisa (Holiday)',
    'Mariah',
    'Mary',
    'Mary (Holiday)',
    'Mary (SR)',
    'Mary (Summer)',
    'Meteon (Event)',
    'Meteon (Holiday)',
    'Mika Jougasaki',
    'Mikasa',
    'Miku Maekawa',
    'Mina',
    'Minami Nitta',
    'Mio Honda',
    'Miria Akagi',
    'Mirin',
    'Mirin (Light)',
    'Mizuki Kawashima',
    'Monika',
    'Monika (Grand)',
    'Naga',
    'Nakoruru',
    'Naoise',
    'Naoise (Event)',
    'Naoise (Summer)',
    'Nene',
    'Nezahualpilli',
    'Nezahualpilli (SR)',
    'Nicholas',
    'Nicholas (Event)',
    'Novei',
    'Owen',
    'Pamela',
    'Paris (Event)',
    'Pecorine',
    'Pengy',
    'Pengy (Event)',
    'Percival',
    'Percival (Event)',
    'Percival (Summer)',
    'Petra',
    'Petra (SSR)',
    'Predator',
    'Rackam',
    'Rackam (Grand)',
    'Rackam (Holiday)',
    'Randall',
    'Randall (SR)',
    'Ranko Kanzaki',
    'Rashid',
    'Richard',
    'Richard (SR)',
    'Rika Jougasaki',
    'Rin Shibuya',
    'Rita',
    'Romeo',
    'Romeo (Event)',
    'Rosamia',
    'Rosamia (SR)',
    'Rosamia (SSR)',
    'Rosine',
    'Rosine (SR)',
    'Ryan',
    'Ryan (SR)',
    'Ryu',
    'Sachiko Koshimizu',
    'Sakura Kinomoto',
    'Sakura Shinguji',
    'Sara',
    'Sara (Event)',
    'Sara (Light)',
    'Sara (Summer)',
    'Seofon',
    'Shiki Ichinose',
    'Shitori',
    'Siegfried',
    'Siegfried (Fire)',
    'Siegfried (Summer)',
    'Sig',
    'Sig (Event)',
    'Silva',
    'Silva (Light)',
    'Sophia',
    'Sophia (SR)',
    'Soriz',
    'Soriz (Event)',
    'Soriz (SSR)',
    'Spinnah',
    'Stahn Aileron',
    'Suzaku Kururugi',
    'Syr (Event)',
    'Tabina',
    'Tanya',
    'Tanya (SR)',
    'Tanya (SSR)',
    'Tanya (Summer)',
    'Tear Grants',
    'Teena',
    'Teena (Summer)',
    'Teena (Valentine)',
    'Teru Tendo',
    'Therese',
    'Therese (Event)',
    'Therese (SSR)',
    'Tōru Amuro',
    'Tsubasa',
    'Tsubasa Kashiwagi',
    'Tweyen',
    'Tyre',
    'Uzuki Shimamura',
    'Vane',
    'Vane (Event)',
    'Vane (SSR)',
    'Viceroy',
    'Vikala',
    'Vira',
    'Vira (Promo)',
    'Vira (SSR)',
    'Vira (Summer)',
    'Vira (Wind)',
    'Volenna',
    'Volenna (Event)',
    'Walder',
    'Walder (Event)',
    'Walder (Holiday)',
    'Walder (Summer)',
    'Will',
    'Will (SR)',
    'Yngwie',
    'Yuri Lowell',
    'Yurius',
    'Zehek',
    'Zehek (Event)',
    'Zeta',
    'Zeta (Dark)',
    'Zeta (Event)',
    'Zeta (Summer)',
    'Zeta and Vaseraga (Halloween)',
    'Μ\'s First-Years',
    'Μ\'s Second-Years',
    'Μ\'s Third-Years'
},
    'erune':{
    'Alanaan',
    'Andira',
    'Andira (Event)',
    'Anthuria',
    'Anthuria (Summer)',
    'Arthur and Mordred',
    'Arusha',
    'Aster',
    'Aster (Event)',
    'Blazing Teacher Elmott',
    'Cailana',
    'Cailana (SR)',
    'Catherine',
    'Catherine (SR)',
    'Cecile',
    'Ceylan (Event)',
    'Chloe',
    'Chloe (Summer)',
    'Drang',
    'Elmott',
    'Elmott (Summer)',
    'Eustace',
    'Eustace (Dark)',
    'Eustace (Halloween)',
    'Feower',
    'Ferry',
    'Ferry (Grand)',
    'Ferry (Halloween)',
    'Ferry (SSR)',
    'Flesselles',
    'Fraux',
    'Freezie',
    'Heles',
    'Heles (Summer)',
    'Heles (Wind)',
    'Helnar',
    'Helnar (Summer)',
    'Ilsa',
    'Ilsa (Light)',
    'Ilsa (Summer)',
    'Karteira',
    'Karteira (SR)',
    'Keehar',
    'Korwa',
    'Korwa (SR)',
    'Korwa (Summer)',
    'Kou',
    'Krugne',
    'Krugne (SR)',
    'La Coiffe',
    'La Coiffe (SR)',
    'Lowain',
    'Lowain (Event)',
    'Lowain (Summer)',
    'Melleau',
    'Metera',
    'Metera (Fire)',
    'Metera (Holiday)',
    'Mishra',
    'Nemone',
    'Nier',
    'Pholia',
    'Sarunan',
    'Sarunan (Dark)',
    'Scathacha',
    'Scathacha (Valentine)',
    'Selfira',
    'Selfira (Event)',
    'Sen',
    'Sen (Holiday)',
    'Sen (SSR)',
    'Seox',
    'Seox (Event)',
    'Seruel',
    'Seruel (Holiday)',
    'Sevastien',
    'Shao',
    'Societte',
    'Societte (Fire)',
    'Societte (Wind)',
    'Stan',
    'Stan (Event)',
    'Stan and Aliza',
    'Sutera',
    'Sutera (Event)',
    'Sutera (Fire)',
    'The Lowain Bros',
    'Thelonim',
    'Tien',
    'Vajra',
    'You (Event)',
    'Yuel',
    'Yuel (Event)',
    'Yuel (Themed)',
    'Yuel (Water)',
    'Yuisis',
    'Yuisis (Fire)',
    'Yuisis (Summer)'
},
    'draph':{
    'Agielba',
    'Aliza',
    'Aliza (Event)',
    'Aliza (Water)',
    'Almeida',
    'Almeida (Summer)',
    'Anila',
    'Anila (Event)',
    'Augusta',
    'Bakura',
    'Baotorda',
    'Baotorda (SSR)',
    'Barawa',
    'Barawa (Event)',
    'Barawa (SR)',
    'Camieux',
    'Camieux (Earth)',
    'Camieux (Summer)',
    'Carmelina',
    'Carmelina (SR)',
    'Daetta',
    'Daetta (SR)',
    'Danua',
    'Danua (Halloween)',
    'Danua (SSR)',
    'Danua (Summer)',
    'Eahta',
    'Forte',
    'Galadar',
    'Galadar (SR)',
    'Garma',
    'Geisenborger',
    'Ghandagoza',
    'Ghandagoza (Summer)',
    'Hallessena',
    'Hallessena (Halloween)',
    'Izmir',
    'Izmir (Summer)',
    'Karva',
    'Karva (SR)',
    'Kumbhira',
    'Kumbhira (Event)',
    'Ladiva',
    'Ladiva (Holiday)',
    'Ladiva (SSR)',
    'Laguna',
    'Lamretta',
    'Lamretta (R)',
    'Lamretta (Water)',
    'Maria Theresa',
    'Mugen',
    'Narmaya',
    'Narmaya (Holiday)',
    'Narmaya (Summer)',
    'Narmaya (Valentine)',
    'Pavidus',
    'Razia',
    'Razia (SR)',
    'Redluck',
    'Reinhardtzar',
    'Sarya',
    'Sarya (Event)',
    'Stan and Aliza',
    'Sturm',
    'Threo',
    'Vanzza',
    'Vanzza (SR)',
    'Vaseraga',
    'Vaseraga (Earth)',
    'Yaia',
    'Yaia (Holiday)',
    'Zaja',
    'Zaja (Halloween)',
    'Zeta and Vaseraga (Halloween)'
},
    'harvin':{
    'Alistair',
    'Anre',
    'Arulumaya',
    'Arulumaya (Holiday)',
    'Arulumaya (Summer)',
    'Balurga',
    'Bridgette',
    'Bridgette and Cordelia',
    'Charlotta',
    'Charlotta (Event)',
    'Charlotta (Halloween)',
    'Charlotta (Light)',
    'Charlotta (Summer)',
    'Drusilla',
    'Elmelaura',
    'Estarriola',
    'Fif',
    'Haaselia',
    'Katzelia',
    'Leonora',
    'Lilele',
    'Lilele (Summer)',
    'Ludmila',
    'Lunalu',
    'Lunalu (SSR)',
    'Lunalu (Summer)',
    'Mahira',
    'Mahira (Event)',
    'Marquiares',
    'Melissabelle',
    'Melissabelle (Valentine)',
    'Milleore',
    'Mimlemel',
    'Mimlemel and Pun-Kin (Halloween)',
    'Mimlemel and Stumpeye',
    'Niyon',
    'Norcel',
    'Philosophia',
    'Philosophia (SR)',
    'Rei',
    'Robertina',
    'Sahli Lao',
    'Sevilbarra',
    'Sevilbarra (Event)',
    'Skull',
    'Skull (Event)',
    'Suframare',
    'Suframare (Summer)',
    'Ulamnuran',
    'Vermeil',
    'Vermeil (SR)',
    'Yodarha',
    'Yodarha (SSR)',
    'Yodarha (Wind)',
    'Zahlhamelina'
},
    'primal':{
    'Alexiel',
    'Alexiel (Summer)',
    'Athena',
    'Azazel',
    'Baal',
    'Cerberus',
    'Colossus',
    'Europa',
    'Europa (Summer)',
    'Grimnir',
    'Grimnir (Valentine)',
    'Halluel and Malluel (Summer)',
    'Lucio',
    'Macula Marius',
    'Medusa',
    'Medusa (Promo)',
    'Medusa (Valentine)',
    'Morrigna',
    'Noa',
    'Noa (Grand)',
    'Olivia',
    'Olivia (Event)',
    'Rosetta (Grand)',
    'Rosetta (Holiday)',
    'Rosetta (Summer)',
    'Sandalphon (Event)',
    'Sandalphon (Summer)',
    'Shiva',
    'Tiamat',
    'Vira (Grand)',
    'Yggdrasil',
    'Zooey',
    'Zooey (Event)',
    'Zooey (Grand)',
    'Zooey (Promo)'
},
    'unknown':{
    'Amira',
    'Amira (Promo)',
    'Arisa',
    'Cassius (Event)',
    'Cassius (Summer)',
    'Erin',
    'Gachapin',
    'Goblin Mage',
    'Grea',
    'Grea (Event)',
    'Grea (Summer)',
    'Helel ben Shalem',
    'Izuminokami Kanesada',
    'Joy (Event)',
    'Karyl',
    'Kokkoro',
    'Lady Katapillar and Vira',
    'Lily',
    'Lily (Event)',
    'Malinda (Event)',
    'Mikazuki Munechika',
    'Milla Maxwell',
    'Morphe and Phoebe (Event)',
    'Nina Drango',
    'Orchid',
    'Robomi',
    'Robomi (Event)',
    'Rosetta',
    'Sophie',
    'Vania',
    'Vania (SR)',
    'Vania and Malinda',
    'Veight',
    'Wulf and Renie',
    'Yamanbagiri Kunihiro',
    'Young Cat (Event)'
},
    'saber':{
    'Agielba',
    'Aglovale',
    'Airi Totoki',
    'Albert',
    'Albert (Event)',
    'Aletheia',
    'Alexiel',
    'Alexiel (Summer)',
    'Anastasia',
    'Ange',
    'Ange (Halloween)',
    'Aoidos',
    'Aqours Second-Years',
    'Arthur (Event)',
    'Arthur and Mordred',
    'Baotorda',
    'Baotorda (SSR)',
    'Beatrix',
    'Beatrix (Halloween)',
    'Beatrix (SR)',
    'Beatrix (Themed)',
    'Black Knight',
    'Bridgette',
    'Bridgette and Cordelia',
    'Carren',
    'Carren (Event)',
    'Charioce XVII',
    'Charlotta',
    'Charlotta (Event)',
    'Charlotta (Halloween)',
    'Charlotta (Light)',
    'Charlotta (Summer)',
    'Colossus',
    'Cordelia',
    'De La Fille',
    'De La Fille (Earth)',
    'De La Fille (Summer)',
    'Farrah',
    'Farrah (Event)',
    'Farrah (SR)',
    'Farrah (Summer)',
    'Gachapin',
    'Gayne',
    'Helnar',
    'Helnar (Summer)',
    'Herja',
    'Herja (SR)',
    'Izmir',
    'Izmir (Summer)',
    'Jeanne d\'Arc',
    'Jeanne d\'Arc (Dark)',
    'Jeanne d\'Arc (Grand)',
    'Jeanne d\'Arc (SR)',
    'Jeanne d\'Arc (Themed)',
    'Jin (Event)',
    'Juri',
    'Juri (Event)',
    'Katalina',
    'Katalina (Grand)',
    'Katalina (Promo)',
    'Katalina (Summer)',
    'Korwa (SR)',
    'Krugne',
    'La Coiffe',
    'La Coiffe (SR)',
    'Lancelot',
    'Lancelot (Event)',
    'Lancelot (Wind)',
    'Lancelot and Vane',
    'Lancelot and Vane (Summer)',
    'Lecia',
    'Lecia (Grand)',
    'Lecia (Summer)',
    'Lecia (Water)',
    'Levi',
    'Levin Sisters',
    'Lina',
    'Lucio',
    'Lucius',
    'Lucius (Fire)',
    'Lucius (SSR)',
    'Maria Theresa',
    'Melissabelle',
    'Melissabelle (Valentine)',
    'Mikasa',
    'Milla Maxwell',
    'Mina',
    'Monika',
    'Monika (Grand)',
    'Naga',
    'Olivia',
    'Olivia (Event)',
    'Owen',
    'Paris (Event)',
    'Pecorine',
    'Percival',
    'Percival (Event)',
    'Percival (Summer)',
    'Rin Shibuya',
    'Romeo',
    'Romeo (Event)',
    'Rosamia',
    'Rosamia (SR)',
    'Rosamia (SSR)',
    'Sandalphon (Event)',
    'Sandalphon (Summer)',
    'Seofon',
    'Seruel',
    'Seruel (Holiday)',
    'Sevastien',
    'Siegfried',
    'Siegfried (Fire)',
    'Siegfried (Summer)',
    'Sig',
    'Stahn Aileron',
    'Stan',
    'Stan (Event)',
    'Stan and Aliza',
    'Sturm',
    'Suzaku Kururugi',
    'Teru Tendo',
    'The Lowain Bros',
    'Thelonim',
    'Therese',
    'Therese (Event)',
    'Therese (SSR)',
    'Threo',
    'Tyre',
    'Uzuki Shimamura',
    'Vermeil (SR)',
    'Vira',
    'Vira (Promo)',
    'Vira (SSR)',
    'Vira (Summer)',
    'Volenna',
    'Volenna (Event)',
    'Will',
    'Will (SR)',
    'Yaia',
    'Yaia (Holiday)',
    'Yodarha',
    'Yodarha (SSR)',
    'Yodarha (Wind)',
    'Yuel',
    'Yuel (Event)',
    'Yuel (Themed)',
    'Yuel (Water)',
    'Yuisis',
    'Yuisis (Fire)',
    'Yuisis (Summer)',
    'Yurius',
    'Zooey (Grand)',
    'Zooey (Promo)'
},
    'dagger':{
    'Azazel',
    'Caim',
    'Carmelina',
    'Carmelina (SR)',
    'Chat Noir',
    'Christina',
    'Danua',
    'Danua (Halloween)',
    'Danua (SSR)',
    'Danua (Summer)',
    'Drusilla',
    'Eustace (Dark)',
    'Ezecrain',
    'Feower',
    'Ferry',
    'Ferry (Grand)',
    'Ferry (Halloween)',
    'Ferry (SSR)',
    'Halluel and Malluel (Summer)',
    'Jamil',
    'Jamil (Dark)',
    'Joker',
    'Kaoru Sakuraba',
    'Lancelot',
    'Lancelot (Event)',
    'Lancelot (Wind)',
    'Leonora',
    'Lowain',
    'Lowain (Event)',
    'Lowain (Summer)',
    'Mika Jougasaki',
    'Nier',
    'Pavidus',
    'Rosetta',
    'Rosetta (Grand)',
    'Rosetta (Holiday)',
    'Rosetta (Summer)',
    'Seruel (Holiday)',
    'Spinnah',
    'Syr (Event)',
    'Tanya',
    'Tanya (SR)',
    'Tanya (SSR)',
    'Tanya (Summer)',
    'The Lowain Bros',
    'Vania',
    'Veight',
    'Vermeil',
    'Walder',
    'Walder (Event)',
    'Walder (Holiday)',
    'Walder (Summer)',
    'Zehek',
    'Zehek (Event)'
},
    'spear':{
    'Anila',
    'Anila (Event)',
    'Anne',
    'Anre',
    'Aqours Third-Years',
    'Athena',
    'Bridgette and Cordelia',
    'Cassius (Event)',
    'Cassius (Summer)',
    'Deliford',
    'Deliford (SR)',
    'Forte',
    'Grimnir',
    'Grimnir (Valentine)',
    'Helel ben Shalem',
    'Heles',
    'Heles (Summer)',
    'Heles (Wind)',
    'Jasmine',
    'Jeanne d\'Arc',
    'Jeanne d\'Arc (Grand)',
    'Juliet',
    'Kokkoro',
    'Kolulu',
    'Kumbhira',
    'Kumbhira (Event)',
    'Lady Grey',
    'Lady Grey (Halloween)',
    'Laguna',
    'Lancelot and Vane',
    'Lancelot and Vane (Summer)',
    'Leona',
    'Leona (Summer)',
    'Mariah',
    'Melleau',
    'Minami Nitta',
    'Naoise',
    'Naoise (Event)',
    'Naoise (Summer)',
    'Nemone',
    'Nezahualpilli',
    'Nezahualpilli (SR)',
    'Razia',
    'Razia (SR)',
    'Rika Jougasaki',
    'Shiva',
    'Sig',
    'Sig (Event)',
    'Ulamnuran',
    'Vane',
    'Vane (Event)',
    'Vane (SSR)',
    'Zeta',
    'Zeta (Dark)',
    'Zeta (Event)',
    'Zeta (Summer)',
    'Zeta and Vaseraga (Halloween)',
    'Zooey (Event)'
},
    'ax':{
    'Abby',
    'Almeida',
    'Almeida (Summer)',
    'Baal',
    'Colossus',
    'Daetta',
    'Daetta (SR)',
    'Danua (SSR)',
    'Elmelaura',
    'Eso',
    'Eso (SR)',
    'Galadar',
    'Galadar (SR)',
    'Gawain',
    'Hallessena',
    'Hallessena (Halloween)',
    'Kumbhira',
    'Kumbhira (Event)',
    'Melissabelle (Valentine)',
    'Melleau',
    'Nemone',
    'Nier',
    'Ryan',
    'Ryan (SR)',
    'Sachiko Koshimizu',
    'Tabina',
    'Threo',
    'Vane',
    'Vane (Event)',
    'Vane (SSR)',
    'Vaseraga',
    'Vaseraga (Earth)',
    'Viceroy',
    'Vikala',
    'Vira (Grand)',
    'Zaja',
    'Zaja (Halloween)',
    'Zeta and Vaseraga (Halloween)'
},
    'staff':{
    'Alanaan',
    'Alistair',
    'Altair',
    'Andira',
    'Andira (Event)',
    'Anna',
    'Anna (SR)',
    'Anna (Summer)',
    'Aqours First-Years',
    'Arulumaya',
    'Arulumaya (Holiday)',
    'Arulumaya (Summer)',
    'Arusha',
    'Blazing Teacher Elmott',
    'Cagliostro',
    'Cagliostro (Dark)',
    'Cagliostro (Event)',
    'Cagliostro (Halloween)',
    'Cagliostro (Summer)',
    'Ceylan (Event)',
    'Chat Noir',
    'Clarisse',
    'Clarisse (Holiday)',
    'Clarisse (Light)',
    'Clarisse (Valentine)',
    'Dante',
    'Dante (SR)',
    'Dante and Freiheit',
    'Drang',
    'Elize Lutus',
    'Elmott',
    'Elmott (Summer)',
    'Erin',
    'Estarriola',
    'Europa',
    'Europa (Summer)',
    'Fif',
    'Goblin Mage',
    'Grimnir',
    'Grimnir (Valentine)',
    'Haaselia',
    'Hazen',
    'Hazen (SR)',
    'Helel ben Shalem',
    'Io',
    'Io (Grand)',
    'Io (Summer)',
    'Jasmine (SR)',
    'Johann',
    'Johann (Event)',
    'Kanako Mimura',
    'Karyl',
    'Korwa',
    'Korwa (Summer)',
    'Koume Shirasaka',
    'Krugne (SR)',
    'Lamretta',
    'Lamretta (R)',
    'Lennah',
    'Lily',
    'Lily (Event)',
    'Lobelia',
    'Luna',
    'Lunalu',
    'Lunalu (SSR)',
    'Lunalu (Summer)',
    'Macula Marius',
    'Magisa',
    'Magisa (Holiday)',
    'Maria Theresa',
    'Marquiares',
    'Miria Akagi',
    'Mishra',
    'Mizuki Kawashima',
    'Morrigna',
    'Noa',
    'Noa (Grand)',
    'Norcel',
    'Petra',
    'Petra (SSR)',
    'Philosophia',
    'Philosophia (SR)',
    'Pholia',
    'Ranko Kanzaki',
    'Rei',
    'Rita',
    'Sakura Kinomoto',
    'Sarunan',
    'Sarunan (Dark)',
    'Shao',
    'Shiki Ichinose',
    'Shiva',
    'Sophia',
    'Sophia (SR)',
    'Suframare',
    'Suframare (Summer)',
    'Tear Grants',
    'Teena',
    'Teena (Summer)',
    'Teena (Valentine)',
    'Tiamat',
    'Vania',
    'Vania (SR)',
    'Vania and Malinda',
    'Will',
    'Will (SR)',
    'Yurius',
    'Zahlhamelina',
    'Μ\'s First-Years',
    'Μ\'s Second-Years',
    'Μ\'s Third-Years'
},
    'gun':{
    'Anzu Futaba',
    'Aqours Second-Years',
    'Aqours Third-Years',
    'Barawa',
    'Barawa (Event)',
    'Barawa (SR)',
    'Black Knight',
    'Camieux',
    'Camieux (Earth)',
    'Camieux (Summer)',
    'Catherine',
    'Catherine (SR)',
    'Christina',
    'Conan Edogawa',
    'Cucouroux',
    'Cucouroux (SSR)',
    'Dorothy',
    'Dorothy and Claudia',
    'Erica Fontaine',
    'Eugen',
    'Eugen (Grand)',
    'Eugen (Summer)',
    'Eustace',
    'Eustace (Dark)',
    'Eustace (Halloween)',
    'Freezie',
    'Friday (Summer)',
    'Garma',
    'Gemini Sunrise',
    'Ilsa',
    'Ilsa (Light)',
    'Ilsa (Summer)',
    'Jessica',
    'Jessica (Event)',
    'Jessica (Summer)',
    'Jessica (Themed)',
    'Joker',
    'Joy (Event)',
    'Karva',
    'Karva (SR)',
    'Lady Katapillar and Vira',
    'Lecia (Water)',
    'Lelouch Lamperouge',
    'Ludmila',
    'Mary',
    'Mary (Holiday)',
    'Mary (SR)',
    'Mary (Summer)',
    'Meteon (Event)',
    'Meteon (Holiday)',
    'Mio Honda',
    'Noa (Grand)',
    'Pengy',
    'Pengy (Event)',
    'Rackam',
    'Rackam (Grand)',
    'Rackam (Holiday)',
    'Razia',
    'Razia (SR)',
    'Richard',
    'Richard (SR)',
    'Robomi',
    'Robomi (Event)',
    'Rosine',
    'Rosine (SR)',
    'Sarya',
    'Sarya (Event)',
    'Silva',
    'Silva (Light)',
    'Skull',
    'Skull (Event)',
    'Tien',
    'Tsubasa Kashiwagi',
    'Tyre',
    'Wulf and Renie',
    'Yngwie',
    'Zooey'
},
    'melee':{
    'Alec',
    'Aliza',
    'Aliza (Event)',
    'Aliza (Water)',
    'Amira',
    'Amira (Promo)',
    'Andira',
    'Anila',
    'Anthuria',
    'Anthuria (Summer)',
    'Ayer',
    'Ayer (Summer)',
    'Azazel',
    'Balurga',
    'Cailana',
    'Cailana (SR)',
    'Caim',
    'Cassius (Event)',
    'Cassius (Summer)',
    'Cerberus',
    'Chloe',
    'Chloe (Summer)',
    'Chun-Li',
    'Claudia',
    'Conan Edogawa',
    'Cure Black and Cure White',
    'Dante and Freiheit',
    'Dorothy and Claudia',
    'Ezecrain (Event)',
    'Feather',
    'Feather (Halloween)',
    'Feather (SR)',
    'Fraux',
    'Friday (Summer)',
    'Gachapin',
    'Geisenborger',
    'Ghandagoza',
    'Ghandagoza (Summer)',
    'Grea',
    'Grea (Event)',
    'Grea (Summer)',
    'Haaselia',
    'Hazen',
    'Hazen (SR)',
    'Ippatsu',
    'Ippatsu (SR)',
    'Ippatsu (Summer)',
    'Joel',
    'Joy (Event)',
    'Kallen Kouzuki',
    'Karin',
    'Karteira',
    'Karteira (SR)',
    'Ladiva',
    'Ladiva (Holiday)',
    'Ladiva (SSR)',
    'Lady Grey',
    'Lady Grey (Halloween)',
    'Lady Katapillar and Vira',
    'Lamretta (Water)',
    'Levin Sisters',
    'Lobelia',
    'Lyria (Event)',
    'Magisa (Holiday)',
    'Mahira',
    'Malinda (Event)',
    'Medusa',
    'Medusa (Promo)',
    'Medusa (Valentine)',
    'Meteon (Holiday)',
    'Miku Maekawa',
    'Mimlemel and Pun-Kin (Halloween)',
    'Mimlemel and Stumpeye',
    'Mugen',
    'Nene',
    'Nina Drango',
    'Orchid',
    'Pengy',
    'Philosophia (SR)',
    'Pholia',
    'Predator',
    'Randall',
    'Randall (SR)',
    'Rashid',
    'Redluck',
    'Reinhardtzar',
    'Ryu',
    'Sara',
    'Sara (Event)',
    'Sara (Light)',
    'Sara (Summer)',
    'Scathacha',
    'Scathacha (Valentine)',
    'Sen',
    'Sen (Holiday)',
    'Sen (SSR)',
    'Seox',
    'Seox (Event)',
    'Skull',
    'Societte',
    'Societte (Fire)',
    'Societte (Wind)',
    'Sophie',
    'Soriz',
    'Soriz (Event)',
    'Soriz (SSR)',
    'Stan and Aliza',
    'Suzaku Kururugi',
    'Tiamat',
    'Tōru Amuro',
    'Tsubasa',
    'Vania and Malinda',
    'Vanzza',
    'Vanzza (SR)',
    'Vikala',
    'Vira (Wind)',
    'Wulf and Renie',
    'Yggdrasil',
    'Yngwie',
    'You (Event)',
    'Young Cat (Event)'
    },
    'bow':{
    'Arisa',
    'Aster',
    'Aster (Event)',
    'Feena',
    'Feena (Event)',
    'Feena (Holiday)',
    'Flesselles',
    'Ilsa',
    'Ilsa (Light)',
    'Ilsa (Summer)',
    'Keehar',
    'Metera',
    'Metera (Fire)',
    'Metera (Holiday)',
    'Milleore',
    'Sahli Lao',
    'Shitori',
    'Sutera',
    'Sutera (Event)',
    'Sutera (Fire)',
    'Tabina',
    'Tweyen',
    'Μ\'s Second-Years'
},
    'harp':{
    'Aoidos',
    'Arriet',
    'Augusta',
    'Baal',
    'Bakura',
    'Cecile',
    'Diantha (Promo)',
    'Diantha (Summer)',
    'Ejaeli',
    'Elta',
    'Elta (Light)',
    'J.J.',
    'J.J. (Summer)',
    'Katzelia',
    'Kou',
    'Lilele',
    'Lilele (Summer)',
    'Mahira',
    'Mahira (Event)',
    'Mimlemel',
    'Mimlemel and Pun-Kin (Halloween)',
    'Morphe and Phoebe (Event)',
    'Mugen',
    'Niyon',
    'Novei',
    'Pamela',
    'Robertina',
    'Selfira',
    'Selfira (Event)',
    'Societte (Wind)',
    'Vira (Wind)',
    'Μ\'s First-Years',
    'Μ\'s Third-Years'
},
    'katana':{
    'Aletheia',
    'Alexiel',
    'Alexiel (Summer)',
    'Cain',
    'Cain (Grand)',
    'Eahta',
    'Gemini Sunrise',
    'Haohmaru',
    'Izuminokami Kanesada',
    'Jin',
    'Jin (Ronin)',
    'Jin (Themed)',
    'Jin (Wind)',
    'Kou',
    'Levi',
    'Lucio',
    'Lucius (SSR)',
    'Mikasa',
    'Mikazuki Munechika',
    'Mirin',
    'Mirin (Light)',
    'Monika',
    'Monika (Grand)',
    'Nakoruru',
    'Narmaya',
    'Narmaya (Holiday)',
    'Narmaya (Summer)',
    'Narmaya (Valentine)',
    'Nicholas',
    'Nicholas (Event)',
    'Rei',
    'Sakura Shinguji',
    'Sandalphon (Event)',
    'Sandalphon (Summer)',
    'Sevilbarra',
    'Sevilbarra (Event)',
    'Shitori',
    'Siegfried',
    'Siegfried (Fire)',
    'Siegfried (Summer)',
    'Vajra',
    'Yamanbagiri Kunihiro',
    'Yodarha',
    'Yodarha (SSR)',
    'Yodarha (Wind)',
    'Yuel',
    'Yuel (Event)',
    'Yuel (Themed)',
    'Yuel (Water)',
    'Yuisis',
    'Yuisis (Fire)',
    'Yuisis (Summer)',
    'Yuri Lowell'
}
}
